spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mlevytfi?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNaming.Strategy
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
